Invoca/process_settings

README.md
Consul uses datacenter with no space so we're standardizing on that.
=> Update README: data_center -> datacenter

CHANGELOG.md, Gemfile.lock, lib/process_settings/monitor.rb, lib/process_settings/version.rb, spec/lib/process_settings/monitor_spec.rb
- Don't check for file_path or logger config if `instance =` has already been called;
it's not necessary.
=> don't check config if instance set

CHANGELOG.md, Gemfile.lock, lib/process_settings/monitor.rb, lib/process_settings/version.rb, spec/lib/process_settings/monitor_spec.rb
* __Issue Link:__ TECH-4291
Adds a new `when_updated` callback registration pattern and deprecates `on_change`
=> Create when updated interface

CHANGELOG.md, Gemfile.lock, lib/process_settings/monitor.rb, lib/process_settings/version.rb
- Reverted rescue syntax to use `begin`/`end` so it will still work with Ruby 2.4.
Note: I temporarily put the `.ruby-version` back to 2.4.2 and ran the tests to prove they pass there.
=> No jira/revert ruby 2.6 syntax

CHANGELOG.md, Gemfile.lock, lib/process_settings/testing/monitor_stub.rb, lib/process_settings/version.rb, spec/lib/process_settings/testing/monitor_stub_spec.rb
Adds the new `#[]` interface to the `MonitorStub` for testing
=> Tech 3417 unify statsd configuration

CHANGELOG.md, lib/process_settings/monitor.rb, lib/process_settings/target.rb, lib/process_settings/version.rb, spec/lib/process_settings/target_spec.rb
When a nested target is provided, and a sub-hash key is missing from the static context, evaluate the targeting as false.
=> Fix non existent nested targeting bug

lib/process_settings/abstract_monitor.rb, lib/process_settings/file_monitor.rb, lib/process_settings/settings.rb, lib/process_settings/target.rb, lib/process_settings/target_and_settings.rb, lib/process_settings/testing/helpers.rb, spec/lib/process_settings/settings_spec.rb, spec/lib/process_settings/target_spec.rb, spec/lib/process_settings/testing/helpers_spec.rb
- Moved default_instance into AbstractMonitor.
- Removed `extend self`.
- Added Target::TRUE_JSON_DOC and `Target.true_target` to extract commonality.
- Fixed a couple exceptions to refer to the now-correct class names.
- Enforce that symbols are not allowed as keys or as values.
=> Tech 4370 update monitor stub to be smarter colin

CHANGELOG.md, Gemfile.lock, bin/diff_process_settings, lib/process_settings/version.rb
- Fixed bug where running `bin/diff_process_settings` multiple times would cause errors by
switching the script to use `Tempdir` for generating temporary file name
=> No jira make diff process settings process safe

CHANGELOG.md, Gemfile.lock, lib/process_settings.rb, lib/process_settings/monitor.rb, lib/process_settings/version.rb, spec/lib/process_settings_spec.rb
- Fixed bug where setting a monitor instance at the `ProcessSettings` and the `ProcessSettings::Monitor`
can cause unexpected errors due to two monitors being configured.
=> No jira fix bug in move to top level singleton

.rspec, CHANGELOG.md, Gemfile.lock, README.md, lib/process_settings/abstract_monitor.rb, lib/process_settings/file_monitor.rb, lib/process_settings/monitor.rb, lib/process_settings/target.rb, lib/process_settings/testing/helpers.rb, lib/process_settings/testing/monitor_stub.rb, lib/process_settings/version.rb, spec/lib/process_settings/file_monitor_spec.rb, spec/lib/process_settings/monitor_spec.rb, spec/lib/process_settings/target_spec.rb, spec/lib/process_settings/testing/helpers_spec.rb, spec/lib/process_settings/testing/monitor_stub_spec.rb, spec/lib/process_settings_spec.rb, spec/spec_helper.rb, spec/support/shared_examples_for_monitors.rb
- `ProcessSettings::Testing::Helpers` now automatically registers an `after`/`teardown` block to
set `ProcessSettings.instance` back to the default that was there before it was optionally
overridden by `stub_process_settings`.
- Moved deprecation from `#initialize` up to `.new` so that warning will point to caller.
- Deprecated lazy `instance` explicitly so that warning will point to caller.
- Cleaned up noisy spec output including deprecation warnings.
- Explicit contract enforcement: `raise ArgumentError` if logger: passed as `nil`.
- Allow 'true' ('1') or 'false' ('0') values for `ENV['DISABLE_LISTEN_CHANGE_MONITORING']`;
default to 'false' when `Rails.env || ENV['SERVICE_ENV']) == 'test'`.
- Fixed memoization of `Target.true_target`.
=> no-jira: deprecate new, fix memoize, and enforce logger contract

CHANGELOG.md, Gemfile.lock, bin/combine_process_settings, lib/process_settings/version.rb, spec/bin/combine_process_settings_spec.rb, spec/bin/diff_process_settings_spec.rb, spec/fixtures/production/combined_process_settings-16-0.yml, spec/fixtures/production/combined_process_settings-16-50.yml, spec/fixtures/production/combined_process_settings-16.yml, spec/fixtures/production/combined_process_settings-18-1.yml, spec/fixtures/production/combined_process_settings-18.yml, spec/fixtures/production/combined_process_settings-18b.yml, spec/fixtures/production/combined_process_settings-19.yml, spec/fixtures/production/combined_process_settings.yml, spec/fixtures/production/settings/honeypot.yml, spec/lib/process_settings/testing/monitor_stub_spec.rb, spec/spec_helper.rb
- `bin/combine_process_settings` now uses an explicit `: null` value for null (nil in Ruby) values, vs.
the former implicit `: ` at end of line. This is important because the trailing space was sometimes deleted
when committed and pushed, depending on editor settings and git(hub) hook configuration.
=> no-jira: explicit null

CHANGELOG.md, Gemfile.lock, bin/combine_process_settings, lib/process_settings/version.rb, process_settings.gemspec, spec/bin/combine_process_settings_spec.rb, spec/bin/diff_process_settings_spec.rb, spec/fixtures/production/combined_process_settings-16-0.yml, spec/fixtures/production/combined_process_settings-16-50.yml, spec/fixtures/production/combined_process_settings-16.yml, spec/fixtures/production/combined_process_settings-18-1.yml, spec/fixtures/production/combined_process_settings-18.yml, spec/fixtures/production/combined_process_settings-18b.yml, spec/fixtures/production/combined_process_settings-19.yml, spec/fixtures/production/combined_process_settings.yml, spec/fixtures/production/settings/honeypot.yml, spec/lib/process_settings/testing/monitor_stub_spec.rb
- Removed explicit `: null` because `libyaml` 0.2.5 doesn't write the trailing space to key off.
Instead, explicitly depend on the `psych` gem and check that libyaml is at least 0.2.5.
=> no-jira/libyaml 0.2.5

CHANGELOG.md, Gemfile.lock, bin/combine_process_settings, lib/process_settings/testing/helpers.rb, lib/process_settings/version.rb, spec/lib/process_settings/testing/helpers_spec.rb
- Fixed `Testing::Helpers` for `minitest` to define a `teardown` method rather than call a `teardown` helper.
=> No jira/fix minitest helpers

CHANGELOG.md, Gemfile.lock, README.md, lib/process_settings/testing/helpers.rb, lib/process_settings/version.rb, spec/lib/process_settings/testing/helpers_spec.rb
- Separated `ProcessSettings::Testing::Minitest::Helpers` from `ProcessSettings::Testing::RSpec::Helpers` since it is difficult
to infer which is which. Left `ProcessSettings::Testing::Helpers` as an alias for `ProcessSettings::Testing::RSpec::Helpers` for
backward-compatibility.
=> no-jira: separate rspec from minitest helpers

README.md
* Added the missing `config.` in the RSpec helper example code
=> Fix typo in RSpec helper example

.gitignore, CHANGELOG.md, Gemfile.lock, lib/process_settings/abstract_monitor.rb, lib/process_settings/version.rb
This is impacting consuming services that were not expecting additional logs at the `info` level.
* Changed the `ProcessSettings::AbstractMonitor` to not log debugging statements for cache hits and miss
=> Update abstract monitor to not log info statements for cache read and write

CHANGELOG.md, Gemfile.lock, README.md, lib/process_settings/file_monitor.rb, lib/process_settings/version.rb, spec/lib/process_settings/file_monitor_spec.rb
Exposes a new method `restart_after_fork` that operates as `start` used to.
=> Tech 4861 add restart after fork method

Gemfile.lock, lib/process_settings/monitor.rb
- Fix deprecated `ProcessSettings::Monitor.logger =` to work with `listen` v3.3.1.
=> No jira/use listen 3.3

CHANGELOG.md, Gemfile.lock, lib/process_settings/abstract_monitor.rb, lib/process_settings/version.rb, spec/lib/process_settings/file_monitor_spec.rb
https://ringrevenue.atlassian.net/browse/TECH-5826
- Fixed a bug where accessing a setting that is a `Hash` defined across multiple file entries
would return the last matching value instead of deep merging the full set of settings
=> Tech 5826 deep merge matching keys

CHANGELOG.md, Gemfile.lock, lib/process_settings/targeted_settings.rb, lib/process_settings/version.rb
* Changed ProcessSettings to directly use `safe_load_file` method.
=> Tech 14900 remove constant evaluation support from process settings gem
